### ISSUE TITLE
Major flaw in the hadronic section of the secondary pulsion drive.

### ISSUE THREAD

**Issue by valdt** [EEwing/KappaGame#6]
The hadronic section is not reacting to stimuli from the pulsion trigger, but the main core does utilize the swap memory to run a high priority hyperthreading update. This might block the pulsion drive from utilizing the energy bank of the ram.

**Comment by EEwing** [comment]
Good point, we've fixed this by attaching the hyperthreading update drive to the pulsion drive via an inelastic tension cable. This should allow enough ram to flow from the energy bank into the main core of the system. Thanks!
